<?php
# This file was automatically generated by the MediaWiki 1.26.3
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}

## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename = "fia";
$wgMetaNamespace = "Fia";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs
## (like /w/index.php/Page_title to /wiki/Page_title) please see:
## https://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath = "/wikinew";
$wgScriptExtension = ".php";
$wgUsePathInfo = false;

## The protocol and server name to use in fully-qualified URLs
#$wgServer = "http://fia.unitec.edu";
$wgServer = "http://localhost";

## The URL path to static resources (images, scripts, etc.)
$wgResourceBasePath = $wgScriptPath;

## The URL path to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
$wgLogo= "$wgResourceBasePath/images/logofi.png";
#$wgLogo = "$wgResourceBasePath/resources/assets/wiki.png";
$wgFavicon = "$wgResourceBasePath/images/favicon.ico";
## UPO means: this is also a user preference option

$wgEnableEmail = true;
$wgEnableUserEmail = false; # UPO

#$wgEmergencyContact = "apache@172.16.5.80";
#$wgPasswordSender = "apache@172.16.5.80";
$wgEmergencyContact = "localhost@localhost";
$wgPasswordSender = "localhost@localhost";

$wgEnotifUserTalk = false; # UPO
$wgEnotifWatchlist = false; # UPO
$wgEmailAuthentication = true;

## Database settings
$wgDBtype = "mysql";
$wgDBserver = "localhost";
$wgDBname = "iscwiki";
$wgDBuser = "wikiuser";
$wgDBpassword = "w3k3@isc";

# MySQL specific settings
$wgDBprefix = "";

# MySQL table options to use during installation or update
$wgDBTableOptions = "ENGINE=InnoDB, DEFAULT CHARSET=binary";

# Experimental charset support for MySQL 5.0.
$wgDBmysql5 = false;

$wgPasswordDefault = 'B';

## Shared memory settings
$wgMainCacheType = CACHE_NONE;
$wgMemCachedServers = array();

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads = true;
#$wgUseImageMagick = true;
#$wgImageMagickConvertCommand = "/usr/bin/convert";

# InstantCommons allows wiki to use images from https://commons.wikimedia.org
$wgUseInstantCommons = false;

## If you use ImageMagick (or any other shell command) on a
## Linux server, this will need to be set to the name of an
## available UTF-8 locale
$wgShellLocale = "en_US.utf8";

## If you want to use image uploads under safe mode,
## create the directories images/archive, images/thumb and
## images/temp, and make them all writable. Then uncomment
## this, if it's not already uncommented:
#$wgHashedUploadDirectory = false;

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publically accessible from the web.
#$wgCacheDirectory = "$IP/cache";

# Site language code, should be one of the list in ./languages/Names.php
$wgLanguageCode = "es";

$wgSecretKey = "5a12e4e7f48fb90a20a99152db09877ad15454e8a4ef141edca9f7e8a8e59986";
#$wgSecretKey = "a40be5c6c863527a24c95a08bdc6bb6a62190f6de913d6d5be5afcbeca3f7b54";

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place

$wgUpgradeKey = "4047c24f45171e56";
#$wgUpgradeKey = "59682dcdc2ce9c0c";

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "https://creativecommons.org/licenses/by-nc-sa/3.0/";
$wgRightsText = "Creative Commons Atribución-NoComercial-CompartirIgual";
$wgRightsIcon = "$wgResourceBasePath/resources/assets/licenses/cc-by-nc-sa.png";

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "";

# The following permissions were set based on your choice in the installer
$wgGroupPermissions['*']['createaccount'] = true;
#$wgWhitelistRead = array("Especial:Crear_una_cuenta");
$wgGroupPermissions['*']['edit'] = false;
$wgShowIPinHeader = false;
$wgGroupPermissions['*']['read'] = true;
$wgGroupPermissions['Docente']= $wgGroupPermissions['user'];

## Default skin: you can change the default skin. Use the internal symbolic
## names, ie 'vector', 'monobook':
$wgDefaultSkin = "vector";

# Enabled skins.
# The following skins were automatically enabled:
wfLoadSkin( 'Vector' );

# Enabled Extensions. Most extensions are enabled by including the base extension file here
# but check specific extension documentation for more details
# The following extensions were automatically enabled:
wfLoadExtension( 'Cite' );
#wfLoadExtension( 'ConfirmEdit' );
wfLoadExtension( 'Gadgets' );
wfLoadExtension( 'ImageMap' );
wfLoadExtension( 'InputBox' );
wfLoadExtension( 'Interwiki' );
wfLoadExtension( 'LocalisationUpdate' );
wfLoadExtension( 'Nuke' );
wfLoadExtension( 'ParserFunctions' );
wfLoadExtension( 'PdfHandler' );
wfLoadExtension( 'Poem' );
wfLoadExtension( 'Renameuser' );
wfLoadExtension( 'SpamBlacklist' );
wfLoadExtension( 'SyntaxHighlight_GeSHi' );
wfLoadExtension( 'TitleBlacklist' );
wfLoadExtension( 'WikiEditor' );
# End of automatically generated settings.
# Add more configuration options below.
require_once("extensions/videoflash.php");
require_once "$IP/extensions/Math/Math.php";
// Set MathML as default rendering option
$wgDefaultUserOptions['math'] = 'mathml';
$wgMathFullRestbaseURL= 'https://api.formulasearchengine.com/';

#ACTUAL RECAPTCHA KEY
#$wgReCaptchaKey = '6Lf6FScTAAAAALUYkubBsTXbHXvdWRA_f9AfhRUb';
#$wgReCaptchaSecret = '6Lf6FScTAAAAAPYZOEJCVS-qt58enTow-fTUc5au';

# RECAPTCHA TEST KEYS
$wgReCaptchaKey = '6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI';
$wgReCaptchaSecret= '6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe';

require_once "$IP/extensions/CustomSidebar/CustomSidebar.php";
$wgDefaultSideBarGroupText['Docente'] = "Template:CustomSidebarDocentes";

#require_once "$IP/extensions/BlockAndNuke/BlockAndNuke.php";
#$wgWhitelist = ("$IP/extensions/BlockAndNuke/whitelist.txt");

# Enable subpages in the main namespace
$wgNamespacesWithSubpages[NS_MAIN] = true;